spring:
  datasource:
    url: jdbc:h2:./db/url-shortener
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: off

server:
  port: 8001